export const AUTH_LOGIN_USER_REQUEST = 'AUTH_LOGIN_USER_REQUEST';
export const AUTH_LOGIN_USER_FAILURE = 'AUTH_LOGIN_USER_FAILURE';
export const AUTH_LOGIN_USER_SUCCESS = 'AUTH_LOGIN_USER_SUCCESS';
export const AUTH_LOGOUT_USER = 'AUTH_LOGOUT_USER';

export const DATA_FETCH_PROTECTED_DATA_REQUEST = 'DATA_FETCH_PROTECTED_DATA_REQUEST';
export const DATA_RECEIVE_PROTECTED_DATA = 'DATA_RECEIVE_PROTECTED_DATA';
export const DATA_LOADING = 'DATA_LOADING';
export const LOADED_JOB = 'LOADED_JOB';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const JOB_LOADING = 'JOB_LOADING';
export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_FAIL = 'FETCH_FAIL';
export const TIMELINE_EXPAND_SUCCESS = 'TIMELINE_EXPAND_SUCCESS';
export const TIMELINE_EXPAND_FAIL = 'TIMELINE_EXPAND_FAIL';
export const COMMENT_SUBMIT_REQUEST = 'COMMENT_SUBMIT_REQUEST';
export const COMMENT_SUBMIT_SUCCESS = 'COMMENT_SUBMIT_SUCCESS';
export const COMMENT_SUBMIT_FAIL = 'COMMENT_SUBMIT_FAIL';
